# Generated by Django 5.1.2 on 2025-01-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind_haven_web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='disability',
            field=models.CharField(choices=[('yes', 'Yes, I have a disability, or have had one in the past'), ('no', 'No, I do not have a disability and have not had one in the past'), ('no_answer', 'I do not want to answer')], default='no', max_length=15),
        ),
        migrations.AddField(
            model_name='contacts',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
    ]
