# Generated by Django 5.1.2 on 2025-01-20 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mind_haven_web_app', '0002_adminuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
